### ISSUE TITLE
Questions about environment in compiled code

### ISSUE THREAD

**Issue by dieggsy** [Adellica/chicken-nrepl#7]
The wiki says: 

> However, sometimes modules disappear due to compiler optimizations.

I've seen this happen - if I connect with nrepl to an interpreted session, I see all the bindings I would expect - defined in file and imported. If it's compiled, I only see those defined in the file. I can then make the same imports manually to get things working as I'd expect.

I was wondering - what sort of optimizations make this happen? Would there be a way to explicitly pass the environment to the call to `eval` in `nrepl-loop` so that it's preserved?

**Comment by kristianlm** [comment]
Good question. I think the answer is pretty complicated. From what I understand, the optimizations and the disappearing exports go hand-in-hand, so it's both or none of them. If you're unable to access procedures from the top-level environment (the REPL), they can no longer be modified. When that's the case, they can be inlined and some checks can be skipped - this_is_ the optimization.

One thing worth making note of is this part of the `csc -h`:

```
     -compile-syntax                macros are made available at run-time
```

As syntax also disappears from your optimized REPL sessions.

The CHICKEN community probably has a better answer than my guess above. Feel free to ask on the [CHICKEN](https://lists.nongnu.org/mailman/listinfo/chicken-users) mailing list and refer them here!
